// SPDX-FileCopyrightText: 2023 Arimah Greene <30327355+arimah@users.noreply.github.com>
// SPDX-FileCopyrightText: 2023 Kara <lunarautomaton6@gmail.com>
// SPDX-FileCopyrightText: 2023 Morb <14136326+Morb0@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Guilherme Ornel <86210200+joshepvodka@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Piras314 <p1r4s@proton.me>
// SPDX-FileCopyrightText: 2024 metalgearsloth <31366439+metalgearsloth@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using Content.Shared.Fax;
using Content.Goobstation.Shared.FaxlessPrinter;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Goobstation.Client.FaxlessPrinter.UI;

[GenerateTypedNameReferences]
public sealed partial class FaxlessPrinterWindow : DefaultWindow
{
    public event Action? FileButtonPressed;
    public event Action? PaperButtonPressed;
    public event Action? CopyButtonPressed;
    public bool OfficePaper = false;

    public FaxlessPrinterWindow()
    {
        RobustXamlLoader.Load(this);

        PaperButtonPressed += OnPaperButtonPressed;

        FileButton.OnPressed += _ => FileButtonPressed?.Invoke();
        PaperButton.OnPressed += _ => PaperButtonPressed?.Invoke();
        CopyButton.OnPressed += _ => CopyButtonPressed?.Invoke();
    }

    public void UpdateState(FaxlessPrinterUiState state)
    {
        CopyButton.Disabled = !state.CanCopy;

        if (state.IsPaperInserted)
        {
            PaperStatusLabel.FontColorOverride = Color.Green;
            PaperStatusLabel.Text = Loc.GetString("fax-machine-ui-paper-inserted");
        }
        else
        {
            PaperStatusLabel.FontColorOverride = Color.Red;
            PaperStatusLabel.Text = Loc.GetString("fax-machine-ui-paper-not-inserted");
        }
    }


    private void OnPaperButtonPressed()
    {
        OfficePaper = !OfficePaper;

        if(OfficePaper)
            PaperButton.Text = Loc.GetString("fax-machine-ui-paper-button-office");
        else
            PaperButton.Text = Loc.GetString("fax-machine-ui-paper-button-normal");
    }
}