using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Client.AutoGenerated;


namespace Content.Goobstation.Client.FaxlessPrinter.UI;

[GenerateTypedNameReferences]
public sealed partial class FaxlessPrinterWindow : DefaultWindow
{
    public event Action? OnSend;
    public event Action? OnLoadPaper;
    public event Action<string>? OnRecipientChanged;
    public bool OfficePaper = false;

    public FaxlessPrinterWindow()
    {
        RobustXamlLoader.Load(this);

        FileButton.OnPressed += _ => OnSend?.Invoke();
        PaperButton.OnPressed += _ => OnLoadPaper?.Invoke();
    }

    public void UpdateState(FaxlessPrinterUiState state)
    {
        CopyButton.Disabled = !state.CanCopy;

        if (state.IsPaperInserted)
        {
            PaperStatusLabel.FontColorOverride = Color.Green;
            PaperStatusLabel.Text = "Paper inserted"; // replace with Loc.GetString if needed
        }
        else
        {
            PaperStatusLabel.FontColorOverride = Color.Red;
            PaperStatusLabel.Text = "Paper not inserted"; // replace with Loc.GetString if needed
        }
    }
}
